FROM quay.io/keycloak/keycloak:26.7.3 AS keycloak-build
ENV KC_HEALTH_ENABLED=true \
    KC_METRICS_ENABLED=true
COPY providers/hzt-bcrypt-legacy/target/hzt-bcrypt-legacy.jar /opt/keycloak/providers/hzt-bcrypt-legacy.jar
RUN /opt/keycloak/bin/kc.sh build --db=postgres

FROM quay.io/keycloak/keycloak:26.7.3
COPY --from=keycloak-build /opt/keycloak/ /opt/keycloak/
