FROM quay.io/keycloak/keycloak:26.7.3 AS keycloak-build
ENV KC_HEALTH_ENABLED=true \
    KC_METRICS_ENABLED=true
COPY providers/hzt-bcrypt-legacy/target/hzt-bcrypt-legacy.jar /opt/keycloak/providers/hzt-bcrypt-legacy.jar
COPY hzt-themes/hzt-data-platform /opt/keycloak/themes/hzt-data-platform
ADD --checksum=sha256:b5022c19c72ff59538c2dc5fd9e15142319a566daad3cb55cedd33fbd2e24872 \
    https://47.108.74.103/data-platform/brand-assets/wedding-hero.jpg \
    /opt/keycloak/themes/hzt-data-platform/login/resources/img/wedding-hero.jpg
RUN /opt/keycloak/bin/kc.sh build --db=postgres

FROM quay.io/keycloak/keycloak:26.7.3
COPY --from=keycloak-build /opt/keycloak/ /opt/keycloak/
